import type { Metadata } from "next";
import { sen, baskervville } from '@/app/fonts'

import "./globals.scss";

import Header from '@/app/components/header/header';
import Footer from '@/app/components/footer/footer';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${sen.variable} ${baskervville.variable}`}>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
