import type { Metadata } from "next";
import { sen, baskervville } from '@/app/fonts'

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sen.variable} ${baskervville.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
