import type { Metadata } from "next";

import Footer from '@/app/components/footer/footer';
import Header from '@/app/components/header/header';

import "./globals.scss";

import { ModalProvider } from '@/app/context/ModalContext';
import { baskervville, libreBaskerville, sen } from '@/app/fonts'

type RootLayoutProps = {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Create Next App",
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
    return (
        <html className={`${sen.variable} ${libreBaskerville.variable} ${baskervville.variable}`} lang="en">
            <body>
                <ModalProvider>
                    <Header />
                    {children}
                    <Footer />
                </ModalProvider>
            </body>
        </html>
    );
}

export default RootLayout;
