import Container from '@/app/components/container/container';

const Privacy: React.FC = () => {
    return (
        <Container className="content">
            <h1>Privacy &amp; Legal</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta venenatis ligula vel consequat. Donec dapibus odio in dolor lacinia maximus. Pellentesque sit amet aliquam mauris, nec tincidunt lorem. Nunc placerat imperdiet felis sit amet condimentum. Phasellus id tellus pretium, bibendum lacus eget, aliquet ipsum. Nam eu iaculis ante. Sed dignissim purus lorem, in consectetur sem pellentesque eget. Donec at scelerisque leo, dictum blandit nisl. Curabitur imperdiet lectus facilisis nisl ullamcorper elementum. Nullam in justo ut tortor blandit gravida eget ac nisl. Vivamus tempor ex turpis, non dictum quam porta vel.</p>
            <p>Proin vitae blandit lectus. Etiam id facilisis risus. Nam a dolor vitae massa finibus sollicitudin vitae eu mauris. Suspendisse vitae iaculis lacus, euismod dapibus elit. Praesent euismod erat sit amet lorem lobortis, nec commodo arcu facilisis. Morbi erat turpis, egestas in tortor quis, vestibulum luctus nibh. Integer hendrerit viverra arcu a dignissim.</p>
            <p>Suspendisse id est sit amet diam vulputate lobortis. Phasellus volutpat metus lacus, quis posuere mi dapibus id. Integer quis pellentesque felis. Nunc eget turpis leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi placerat efficitur accumsan. Nulla mollis enim tincidunt tortor mollis, nec lacinia purus pellentesque. Quisque eget erat non est feugiat fringilla id eu ligula. Sed velit felis, euismod at nibh eu, ultrices posuere neque. Ut a tellus quis nunc commodo mattis sed finibus urna. Proin volutpat ornare justo, at tristique odio fringilla vitae. Maecenas vulputate arcu sed magna placerat volutpat. Aliquam ac ligula urna. Nullam finibus diam eget magna consequat vestibulum. Donec fringilla est quis velit commodo porttitor.
            </p>
            <p>Vivamus ultrices tellus suscipit tellus sagittis aliquam. Morbi faucibus eget quam et dignissim. Duis erat nunc, ultrices a mattis vitae, porttitor a nisi. Proin ornare sapien vitae quam tempus, sed pharetra lectus blandit. Quisque feugiat dictum eros, vel ullamcorper risus eleifend et. Ut molestie accumsan odio, at tempor quam maximus nec. Donec pellentesque risus arcu, in sollicitudin mi laoreet id. Maecenas nec nibh nec erat pretium egestas quis id sapien. Fusce pulvinar dui rhoncus erat ornare, ut mattis risus viverra. Integer pretium enim sit amet porttitor suscipit. Fusce placerat pellentesque elit, aliquam viverra ante pulvinar iaculis. Aenean finibus tortor laoreet nunc ultricies, quis luctus odio tempor.</p>
            <p>Proin luctus mollis sapien, in aliquet nibh tristique at. Nam sollicitudin vehicula metus, id molestie est bibendum eu. Aliquam semper dictum vestibulum. Curabitur sit amet eros eget arcu bibendum pellentesque. Nulla at pulvinar elit, quis consequat lacus. Praesent hendrerit tempor urna at varius. Donec eu dui eget nulla consectetur mollis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta venenatis ligula vel consequat. Donec dapibus odio in dolor lacinia maximus. Pellentesque sit amet aliquam mauris, nec tincidunt lorem. Nunc placerat imperdiet felis sit amet condimentum. Phasellus id tellus pretium, bibendum lacus eget, aliquet ipsum. Nam eu iaculis ante. Sed dignissim purus lorem, in consectetur sem pellentesque eget. Donec at scelerisque leo, dictum blandit nisl. Curabitur imperdiet lectus facilisis nisl ullamcorper elementum. Nullam in justo ut tortor blandit gravida eget ac nisl. Vivamus tempor ex turpis, non dictum quam porta vel.</p>
        </Container>
    )
}

export default Privacy;
